import { CampaignLevelConfig, Wall } from '../types/game';

// Helper to construct pre-placed neutral walls
function createWall(id: string, x: number, y: number, orientation: 'H' | 'V'): Wall {
  return {
    id,
    x,
    y,
    orientation,
    placedBy: -1, // -1 denotes neutral/pre-placed puzzle barrier
  };
}

export const CAMPAIGN_LEVELS: CampaignLevelConfig[] = [
  // ====================================================================
  // TIER 1: THE BASICS (Levels 1–5)
  // Easy AI, open boards, straight jumps, basic defensive blocking
  // ====================================================================
  {
    levelNumber: 1,
    title: 'First Steps',
    subtitle: 'Learn basic pawn movement & race fundamentals',
    tier: 'basics',
    aiDifficulty: 'easy',
    botName: 'Trainee Bot',
    botAvatar: 'minty',
    playerWalls: 10,
    opponentWalls: 10,
    preplacedWalls: [],
    turnTimerSeconds: 45,
    parMoves: 10,
    objective: 'Race your pawn to the opposite baseline (Row 8) before the trainee.',
    rewardStickerSlug: 'geo-rhombus',
  },
  {
    levelNumber: 2,
    title: 'The First Barrier',
    subtitle: 'Navigating around obstacles',
    tier: 'basics',
    aiDifficulty: 'easy',
    botName: 'Scout Bot',
    botAvatar: 'minty',
    playerWalls: 10,
    opponentWalls: 10,
    preplacedWalls: [
      createWall('c2-w1', 3, 3, 'H'),
    ],
    turnTimerSeconds: 45,
    parMoves: 12,
    objective: 'Flank around the pre-placed center barricade and reach the goal.',
    rewardStickerSlug: 'smiley-classic',
  },
  {
    levelNumber: 3,
    title: 'Defensive Reflex',
    subtitle: 'Learn to place blocking walls',
    tier: 'basics',
    aiDifficulty: 'easy',
    botName: 'Blocker Bot',
    botAvatar: 'dino',
    playerWalls: 10,
    opponentWalls: 10,
    preplacedWalls: [],
    turnTimerSeconds: 40,
    parMoves: 14,
    objective: 'Place strategic horizontal walls to delay the opponent pawn while advancing.',
    rewardStickerSlug: 'pixel-heart',
  },
  {
    levelNumber: 4,
    title: 'Corridor Squeeze',
    subtitle: 'Funneled passage tactics',
    tier: 'basics',
    aiDifficulty: 'easy',
    botName: 'Sentry Bot',
    botAvatar: 'dino',
    playerWalls: 8,
    opponentWalls: 8,
    preplacedWalls: [
      createWall('c4-w1', 1, 3, 'V'),
      createWall('c4-w2', 5, 3, 'V'),
    ],
    turnTimerSeconds: 40,
    parMoves: 14,
    objective: 'Navigate through the center corridor and prevent the opponent from cutting through.',
    rewardStickerSlug: 'checker-tag',
  },
  {
    levelNumber: 5,
    title: 'The Leapfrog',
    subtitle: 'Mastering pawn jump mechanics',
    tier: 'basics',
    aiDifficulty: 'easy',
    botName: 'Jumper Bot',
    botAvatar: 'minty',
    playerWalls: 8,
    opponentWalls: 8,
    preplacedWalls: [
      createWall('c5-w1', 2, 4, 'H'),
      createWall('c5-w2', 4, 4, 'H'),
    ],
    turnTimerSeconds: 35,
    parMoves: 13,
    objective: 'Face your opponent in the corridor and execute a straight hop over them.',
    rewardStickerSlug: 'barcode-99',
  },

  // ====================================================================
  // TIER 2: TACTICAL PUZZLES (Levels 6–15)
  // Asymmetric constraints (e.g. 3 walls vs 10), pre-placed neutral labyrinths
  // ====================================================================
  {
    levelNumber: 6,
    title: 'Wall Scarcity',
    subtitle: 'Asymmetric: 3 Walls vs 10 Opponent Walls',
    tier: 'tactical',
    aiDifficulty: 'normal',
    botName: 'Tactician Alpha',
    botAvatar: 'dino',
    playerWalls: 3,
    opponentWalls: 10,
    preplacedWalls: [],
    turnTimerSeconds: 30,
    parMoves: 16,
    objective: 'Win with only 3 walls! Conserve every wall for critical turning points.',
    rewardStickerSlug: 'cross-bones',
  },
  {
    levelNumber: 7,
    title: 'The Serpentine',
    subtitle: 'Winding S-Curve labyrinth navigation',
    tier: 'tactical',
    aiDifficulty: 'normal',
    botName: 'Maze Runner',
    botAvatar: 'dino',
    playerWalls: 6,
    opponentWalls: 6,
    preplacedWalls: [
      createWall('c7-w1', 1, 2, 'H'),
      createWall('c7-w2', 3, 2, 'H'),
      createWall('c7-w3', 3, 5, 'H'),
      createWall('c7-w4', 5, 5, 'H'),
    ],
    turnTimerSeconds: 30,
    parMoves: 18,
    objective: 'Weave through the pre-placed serpentine barriers while sealing the opponent off.',
    rewardStickerSlug: 'holo-tokyo',
  },
  {
    levelNumber: 8,
    title: 'The Fortress Gate',
    subtitle: 'Cracking fortified positions',
    tier: 'tactical',
    aiDifficulty: 'normal',
    botName: 'Siege Warden',
    botAvatar: 'blaze',
    playerWalls: 5,
    opponentWalls: 9,
    preplacedWalls: [
      createWall('c8-w1', 2, 6, 'H'),
      createWall('c8-w2', 4, 6, 'H'),
      createWall('c8-w3', 1, 6, 'V'),
      createWall('c8-w4', 5, 6, 'V'),
    ],
    turnTimerSeconds: 30,
    parMoves: 19,
    objective: 'Breach the fortified defensive pocket and outpace the warden.',
    rewardStickerSlug: 'holographic-prism',
  },
  {
    levelNumber: 9,
    title: 'The Narrow Strait',
    subtitle: 'Channeling movement down the center',
    tier: 'tactical',
    aiDifficulty: 'normal',
    botName: 'Strait Marshal',
    botAvatar: 'dino',
    playerWalls: 5,
    opponentWalls: 8,
    preplacedWalls: [
      createWall('c9-w1', 0, 3, 'V'),
      createWall('c9-w2', 0, 5, 'V'),
      createWall('c9-w3', 6, 3, 'V'),
      createWall('c9-w4', 6, 5, 'V'),
    ],
    turnTimerSeconds: 30,
    parMoves: 17,
    objective: 'Control the narrow center channel without allowing yourself to be blocked in.',
    rewardStickerSlug: 'retro-cassette',
  },
  {
    levelNumber: 10,
    title: 'Asymmetric Siege',
    subtitle: 'Asymmetric: 4 Walls vs 10 Walls',
    tier: 'tactical',
    aiDifficulty: 'normal',
    botName: 'Fortress Tactician',
    botAvatar: 'blaze',
    playerWalls: 4,
    opponentWalls: 10,
    preplacedWalls: [],
    turnTimerSeconds: 25,
    parMoves: 18,
    objective: 'Survive a heavy 10-wall barrage while making every one of your 4 walls count.',
    rewardStickerSlug: 'cyber-lotus',
  },
  {
    levelNumber: 11,
    title: 'Pinwheel Maze',
    subtitle: 'Rotating symmetry obstacle',
    tier: 'tactical',
    aiDifficulty: 'normal',
    botName: 'Vortex Bot',
    botAvatar: 'blaze',
    playerWalls: 6,
    opponentWalls: 6,
    preplacedWalls: [
      createWall('c11-w1', 2, 2, 'H'),
      createWall('c11-w2', 4, 2, 'V'),
      createWall('c11-w3', 4, 4, 'H'),
      createWall('c11-w4', 2, 4, 'V'),
    ],
    turnTimerSeconds: 25,
    parMoves: 20,
    objective: 'Solve the rotating vortex obstacle and counter the bot’s detour strategy.',
    rewardStickerSlug: 'glitch-cat',
  },
  {
    levelNumber: 12,
    title: 'The Gauntlet Trench',
    subtitle: 'Deep horizontal barrier splits',
    tier: 'tactical',
    aiDifficulty: 'normal',
    botName: 'Trench Guard',
    botAvatar: 'blaze',
    playerWalls: 5,
    opponentWalls: 8,
    preplacedWalls: [
      createWall('c12-w1', 1, 3, 'H'),
      createWall('c12-w2', 3, 3, 'H'),
      createWall('c12-w3', 4, 5, 'H'),
      createWall('c12-w4', 6, 5, 'H'),
    ],
    turnTimerSeconds: 25,
    parMoves: 21,
    objective: 'Force the opponent around the deep trenches while keeping your route clear.',
    rewardStickerSlug: 'animated-skull',
  },
  {
    levelNumber: 13,
    title: 'Tactical Ambush',
    subtitle: 'Asymmetric: 4 Walls vs 9 Walls with pre-placed barriers',
    tier: 'tactical',
    aiDifficulty: 'normal',
    botName: 'Ambush Master',
    botAvatar: 'blaze',
    playerWalls: 4,
    opponentWalls: 9,
    preplacedWalls: [
      createWall('c13-w1', 2, 1, 'H'),
      createWall('c13-w2', 5, 6, 'H'),
    ],
    turnTimerSeconds: 25,
    parMoves: 19,
    objective: 'Overcome disadvantaged wall count and opponent positioning.',
    rewardStickerSlug: 'electric-dragon',
  },
  {
    levelNumber: 14,
    title: 'The Labyrinth Core',
    subtitle: '6 Neutral barriers forming complex intersections',
    tier: 'tactical',
    aiDifficulty: 'normal',
    botName: 'Minotaur Bot',
    botAvatar: 'blaze',
    playerWalls: 5,
    opponentWalls: 7,
    preplacedWalls: [
      createWall('c14-w1', 1, 2, 'V'),
      createWall('c14-w2', 2, 4, 'H'),
      createWall('c14-w3', 4, 3, 'V'),
      createWall('c14-w4', 5, 5, 'H'),
      createWall('c14-w5', 6, 2, 'V'),
      createWall('c14-w6', 3, 6, 'H'),
    ],
    turnTimerSeconds: 20,
    parMoves: 22,
    objective: 'Navigate the dense labyrinth core and out-calculate the Minotaur.',
    rewardStickerSlug: 'flame-thrower',
  },
  {
    levelNumber: 15,
    title: 'Trial of the Centurion',
    subtitle: 'Extreme Asymmetry: 3 Walls vs 10 Walls with Normal Bot',
    tier: 'tactical',
    aiDifficulty: 'normal',
    botName: 'Centurion Guard',
    botAvatar: 'blaze',
    playerWalls: 3,
    opponentWalls: 10,
    preplacedWalls: [
      createWall('c15-w1', 3, 4, 'H'),
    ],
    turnTimerSeconds: 20,
    parMoves: 18,
    objective: 'Conquer the Centurion with only 3 walls! Unlocks signature Gauntlet Master sticker.',
    rewardStickerSlug: 'gauntlet-master',
  },

  // ====================================================================
  // TIER 3: MASTER TRIALS (Levels 16+)
  // AlphaZero-style depth-4 bots with turn timers (15s blitz)
  // ====================================================================
  {
    levelNumber: 16,
    title: 'Blitz Trial: Initiation',
    subtitle: 'Alpha Master Bot with 15s Blitz Timer',
    tier: 'master',
    aiDifficulty: 'grandmaster',
    botName: 'AlphaZero-4 [Blitz]',
    botAvatar: 'blaze',
    playerWalls: 10,
    opponentWalls: 10,
    preplacedWalls: [],
    turnTimerSeconds: 15,
    parMoves: 20,
    objective: 'Think fast! 15 seconds per turn against a 2-Ply AlphaZero Minimax engine.',
    rewardStickerSlug: 'vapor-statue',
  },
  {
    levelNumber: 17,
    title: 'Blitz Trial: The Crossfire',
    subtitle: 'Grandmaster AI + 15s Blitz + Neutral Cross',
    tier: 'master',
    aiDifficulty: 'grandmaster',
    botName: 'AlphaZero-4 [Crossfire]',
    botAvatar: 'blaze',
    playerWalls: 8,
    opponentWalls: 8,
    preplacedWalls: [
      createWall('c17-w1', 3, 3, 'H'),
      createWall('c17-w2', 3, 4, 'V'),
    ],
    turnTimerSeconds: 15,
    parMoves: 22,
    objective: 'Handle tight corridor tactics at blitz speed.',
    rewardStickerSlug: 'gold-quoridor-crown',
  },
  {
    levelNumber: 18,
    title: 'Blitz Trial: Asymmetric Blitz',
    subtitle: 'Player 5 Walls vs Bot 10 Walls with 15s Timer',
    tier: 'master',
    aiDifficulty: 'grandmaster',
    botName: 'AlphaZero-4 [Overlord]',
    botAvatar: 'blaze',
    playerWalls: 5,
    opponentWalls: 10,
    preplacedWalls: [],
    turnTimerSeconds: 15,
    parMoves: 21,
    objective: 'Overcome severe wall deficit against AlphaZero under 15-second blitz pressure.',
    rewardStickerSlug: 'alpha-oracle-eye',
  },
  {
    levelNumber: 19,
    title: 'Blitz Trial: Labyrinth Blitz',
    subtitle: 'Grandmaster AI + 15s Timer + 4 Neutral Labyrinth Barriers',
    tier: 'master',
    aiDifficulty: 'grandmaster',
    botName: 'AlphaZero-4 [Architect]',
    botAvatar: 'blaze',
    playerWalls: 6,
    opponentWalls: 8,
    preplacedWalls: [
      createWall('c19-w1', 1, 2, 'H'),
      createWall('c19-w2', 2, 5, 'V'),
      createWall('c19-w3', 5, 2, 'V'),
      createWall('c19-w4', 4, 5, 'H'),
    ],
    turnTimerSeconds: 15,
    parMoves: 24,
    objective: 'Calculate multi-path detours instantly under 15-second blitz timer.',
    rewardStickerSlug: 'diamond-shield',
  },
  {
    levelNumber: 20,
    title: 'Grandmaster Alpha Trial',
    subtitle: 'The Ultimate ADINOMIDE Test: 15s Blitz, 6 vs 10 Walls, AlphaZero Engine',
    tier: 'master',
    aiDifficulty: 'grandmaster',
    botName: 'AlphaZero Supreme',
    botAvatar: 'blaze',
    playerWalls: 6,
    opponentWalls: 10,
    preplacedWalls: [
      createWall('c20-w1', 3, 4, 'H'),
      createWall('c20-w2', 4, 3, 'V'),
    ],
    turnTimerSeconds: 15,
    parMoves: 22,
    objective: 'The pinnacle of ADINOMIDE mastery. Defeat AlphaZero Supreme to claim undisputed championship glory.',
    rewardStickerSlug: 'speed-demon',
  },
];

export function getCampaignLevel(levelNumber: number): CampaignLevelConfig {
  const found = CAMPAIGN_LEVELS.find((l) => l.levelNumber === levelNumber);
  return found || CAMPAIGN_LEVELS[0];
}

export function getStarsForLevel(movesTaken: number, parMoves: number, isWin: boolean): number {
  if (!isWin) return 0;
  if (movesTaken <= parMoves) return 3;
  if (movesTaken <= parMoves + 5) return 2;
  return 1;
}
